### ISSUE TITLE
Homebrew throws warnings about deprecated sha1 function

### ISSUE THREAD

**Issue by morganestes** [victor/whereami#22]
When I run `brew upgrade` on my packages, whereami throws multiple warnings:

```
Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Library/Taps/victor/homebrew-whereami/whereami.rb:6:in `<class:Whereami>'
Please report this to the victor/whereami tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Library/Taps/victor/homebrew-whereami/whereami.rb:6:in `<class:Whereami>'
Please report this to the victor/whereami tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/victor/homebrew-whereami/whereami.rb:6:in `<class:Whereami>'
Please report this to the victor/whereami tap!
```

**Comment by JayBrown** [comment]
You can also use CoreLocationCLI: https://github.com/fulldecent/corelocationcli
It still needs some improvements, but at least it's working without major errors.
